module GeneratedRegressionTestData exposing (..)

import RegressionTest.Runner exposing (UpdateFunctionTestData)


testData : List UpdateFunctionTestData
testData =
    [ { initialModel = "0"
      , messages =
          [ "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          ]
      , expectedOutput = "-1"
      }
    , { initialModel = "0"
      , messages =
          [ "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          ]
      , expectedOutput = "-3"
      }
    , { initialModel = "0"
      , messages =
          [ "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          ]
      , expectedOutput = "-4"
      }
    , { initialModel = "0"
      , messages =
          [ "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          ]
      , expectedOutput = "0"
      }
    , { initialModel = "0"
      , messages =
          [ "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          ]
      , expectedOutput = "8"
      }
    , { initialModel = "0"
      , messages =
          [ "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          ]
      , expectedOutput = "3"
      }
    , { initialModel = "0"
      , messages =
          [ "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          ]
      , expectedOutput = "-2"
      }
    , { initialModel = "0"
      , messages =
          [ "\"DECREMENT\"", "\"INCREMENT\"", "\"DECREMENT\"", "\"DECREMENT\"", "\"DECREMENT\"", "\"INCREMENT\"" ]
      , expectedOutput = "-2"
      }
    , { initialModel = "0"
      , messages =
          [ "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          , "\"INCREMENT\""
          , "\"INCREMENT\""
          , "\"DECREMENT\""
          ]
      , expectedOutput = "2"
      }
    , { initialModel = "0", messages = [ "\"INCREMENT\"", "\"DECREMENT\"", "\"DECREMENT\"" ], expectedOutput = "-1" }
    ]
